image: node:10.16.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@8.3.13
    - npm install
    - ng build --prod
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
