image: node:10.16.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@9.0.1
    - npm install -g gzipper
    - npm install
    - npm run build:ssr
    - npm run prerender
    - cp dist/DashboardSystem/theme/404/index.html dist/DashboardSystem/404.html
    - gzipper --verbose ./dist/DashboardSystem
  artifacts:
    paths:
      - dist/DashboardSystem
  only:
    - master
    - pages
