image: node:10.16.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@9.1.10
    - npm install -g gzipper
    - npm install
    - npm run build:ssr
    - npm run prerender
    - cp public/theme/404/index.html public/404.html
    - gzipper --verbose ./public
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
