image: node:10.16.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@12.0.4
    - npm install -g gzipper@3.7.0
    - npm install
    - npm run build:ssr
    - npm run prerender
    - cp public/theme/404/index.html public/404.html
    - gzipper --verbose ./public
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
