image: node:10.16.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@8.3.14
    - npm install
    - ng build --prod --base-href=/
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
