image: node:10.16.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@9.0.1
    - npm install -g gzipper
    - npm install
    - ng build --prod --base-href=/
    - ng run DashboardSystem:server
    - npx angular-prerender
    - cp public/theme/404/index.html public/404.html
    - gzipper --verbose ./public
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
