# Site settings
title: Dashboard System Website
email: brandonabela9@gmail.com
baseurl: "" # the sub path of your site
url: "/" # the base hostname & protocol for your site
twitter_username: brandonabela
github_username:  abela_brandon

# Build settings
markdown: kramdown
exclude: ["README.md"]
